version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    tty: true
    env_file: ./.env
    ports:
      - "8080:8080"
    depends_on:
      - redis
  redis:
    image: "redis:6.2.7"
    ports:
      - "6379:6379"
    volumes:
      - "./data/:/data"

